### ISSUE TITLE
Failed to connect to server on first connect 

### ISSUE THREAD

**Issue by barry-sr** [mongo-js/mongojs#341]
I try to connect to mlab database by using the link provided when i run thehttp://localhost:3000/api/feedbacks then i got this error bellow from the console 

MongoError: failed to connect to server [ds113566.mlab.com:13566] on first connect [MongoError: connect ETIMEDOUT 54.158.46.240:13566]
    at Pool.<anonymous> (C:\Users\Barry\Desktop\TaxiMoto\server\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (C:\Users\Barry\Desktop\TaxiMoto\server\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Connection.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (C:\Users\Barry\Desktop\TaxiMoto\server\node_modules\mongodb-core\lib\connection\connection.js:187:49)
    at Socket.g (events.js:292:16)
    at emitOne (events.js:96:13)
[nodemon] app crashed - waiting for file changes before starting...

so any help

**Comment by tankoanoamos** [comment]
Did you get help ? 
I have the same problem since 5 days

**Comment by vijay-dadhich09** [comment]
I am also facing the same problem

**Comment by yannickmaroyi** [comment]
i just found out mongojs is not connecting to mlab has anyone found a way to fix it
